Minor docstring fixes in formulary
PlasmaPy/PlasmaPy pull request #1058
Opened 2021-03-09 23:16 UTC by namurphy

Here's a PR of some minor fixes mostly related to reStructuredText formatting that I've been meaning to work on a while now.  My main motivation is that there are some exceptions and warnings that show up like **~astropy.whatever.SomeError** rather than as a linked object.  I might make a few minor PEP 8 fixes here and there too, such as for variable names.

I don't know if we've settled on conventions regarding the specific formatting of references, warnings, etc.  I'm mostly concerned about consistency and links here, so I'm open to different conventions.

2021-03-10 05:00 UTC, rocco8773 requested changes
Fairly straight forward, just a few things here and there.

2021-03-10 13:32 UTC, StanczakDominik commented on plasmapy/formulary/parameters.py
> +        N_D = \frac{4π}{3} n_e λ_D^3
Does this actually work? I mean, can I put unicodes in when writing plain old latex? Because if so, this changes *everything*.

2021-03-10 14:18 UTC, StanczakDominik commented
Is this still in the draft stage? :)

2021-03-10 15:43 UTC, namurphy commented
> Is this still in the draft stage? :)

Yep...I still need to double check that my fixes are actually *fixes* and not making things worse.  I should be able to get that done within the next few hours.  Statistically, it's an improvement, at least? And thank you to @rocco8773 for the quick review!

2021-03-11 00:31 UTC, namurphy commented
Ok...I think I should stop working on this since there are lots of tiny fixes that I've made and could still make.  Ready for (perhaps a statistical) review, I guess?

2021-03-11 04:00 UTC, Tiger-Du requested changes
Suggested changes below.

From comparing the latest build of the docs to this build, it seems that backticks around the errors in the "Raises" section do not change anything. Not sure why...

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/radiation.py
>      where   :math:`k_{max}` is a maximum wavenumber approximated here as
```suggestion
    where :math:`k_{max}` is a maximum wavenumber approximated here as
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/quantum.py
>      energy_F : ~astropy.units.Quantity
```suggestion
    energy_F : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/dimensionless.py
> +    Rm: `~astropy.units.Quantity`
```suggestion
    Rm : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/quantum.py
> +    n_e : ~astropy.units.Quantity
```suggestion
    n_e : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/quantum.py
>      --------
```suggestion
    Warns
    -----
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/relativity.py
> +    `~astropy.units.UnitsWarning`
```suggestion
    : `~astropy.units.UnitsWarning`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/dimensionless.py
>      B : ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
        The temperature of the plasma.

    n : `~astropy.units.Quantity`
        The particle density of the plasma.

    B : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/dimensionless.py
> +    theta: `~astropy.units.Quantity`
```suggestion
    theta : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/dielectric.py
>      B : ~astropy.units.Quantity
```suggestion
    B : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/dielectric.py
>      species : list of str
```suggestion
    species : `list` of `str`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/braginskii.py
> +    ~astropy.units.quantity.Quantity
```suggestion
    `~astropy.units.quantity.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/braginskii.py
> +    ~astropy.units.quantity.Quantity
```suggestion
    `~astropy.units.quantity.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/braginskii.py
> +    ~astropy.units.quantity.Quantity
```suggestion
    `~astropy.units.quantity.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/braginskii.py
> +    ~astropy.units.quantity.Quantity
```suggestion
    `~astropy.units.quantity.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/braginskii.py
> +        ~astropy.units.quantity.Quantity
```suggestion
        `~astropy.units.quantity.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/braginskii.py
> +        ~astropy.units.quantity.Quantity
```suggestion
        `~astropy.units.quantity.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/braginskii.py
> +        ~astropy.units.quantity.Quantity
```suggestion
        `~astropy.units.quantity.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/braginskii.py
> +        ~astropy.units.quantity.Quantity
```suggestion
        `~astropy.units.quantity.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      V : ~astropy.units.Quantity, optional
```suggestion
    V : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      method : str, optional
```suggestion
    method : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      V : ~astropy.units.Quantity, optional
```suggestion
    V : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      V : ~astropy.units.Quantity, optional
```suggestion
    V : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      method : str, optional
```suggestion
    method : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      V : ~astropy.units.Quantity, optional
```suggestion
    V : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      V : ~astropy.units.Quantity, optional
```suggestion
    V : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      method : str, optional
```suggestion
    method : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
> +    `RelativityError`
```suggestion
    `~plasmapy.utils.exceptions.RelativityError`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      RelativityError
```suggestion
    `~plasmapy.utils.exceptions.RelativityError`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      RelativityError
```suggestion
    `~plasmapy.utils.exceptions.RelativityError`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
> +    `RelativityError`
```suggestion
    `~plasmapy.utils.exceptions.RelativityError`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
> +    `RelativityError`
```suggestion
    `~plasmapy.utils.exceptions.RelativityError`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
> +    `RelativityError`
```suggestion
    `~plasmapy.utils.exceptions.RelativityError`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      V : ~astropy.units.Quantity, optional
```suggestion
    V : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      V : ~astropy.units.Quantity, optional
```suggestion
    V : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      method : str, optional
```suggestion
    method : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/collisions.py
>      V : ~astropy.units.Quantity, optional
```suggestion
    V : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      T: ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      particle: str, optional
```suggestion
    particle : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      T: ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      particle: str, optional
```suggestion
    particle : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      vx_drift: ~astropy.units.Quantity, optional
```suggestion
    vx_drift : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      vy_drift: ~astropy.units.Quantity, optional
```suggestion
    vy_drift : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      vTh: ~astropy.units.Quantity, optional
```suggestion
    vTh : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      vx: ~astropy.units.Quantity
```suggestion
    vx : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      vy: ~astropy.units.Quantity
```suggestion
    vy : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      T: ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      particle: str, optional
```suggestion
    particle : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      vx_drift: ~astropy.units.Quantity, optional
```suggestion
    vx_drift : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      vTh: ~astropy.units.Quantity, optional
```suggestion
    vTh : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      units: str, optional
```suggestion
    units : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      T: ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      particle: str, optional
```suggestion
    particle : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      v_drift: ~astropy.units.Quantity
```suggestion
    v_drift : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      vTh: ~astropy.units.Quantity, optional
```suggestion
    vTh : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      units: str, optional
```suggestion
    units : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      T: ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      v_drift: ~astropy.units.Quantity
```suggestion
    v_drift : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      vTh: ~astropy.units.Quantity, optional
```suggestion
    vTh : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      units: str, optional
```suggestion
    units : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      T: ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      particle: str, optional
```suggestion
    particle : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      T: ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      kappa: ~astropy.units.Quantity
```suggestion
    kappa : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      T: ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
>      kappa: ~astropy.units.Quantity
```suggestion
    kappa : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
> +    particle: `str`, optional
```suggestion
    particle : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
> +    vx_drift: `~astropy.units.Quantity`, optional
```suggestion
    vx_drift : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
> +    vy_drift: `~astropy.units.Quantity`, optional
```suggestion
    vy_drift : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
> +    vz_drift: `~astropy.units.Quantity`, optional
```suggestion
    vz_drift : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/distribution.py
> +    vTh: `~astropy.units.Quantity`, optional
```suggestion
    vTh : `~astropy.units.Quantity`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      n_e : ~astropy.units.Quantity
```suggestion
    n_e : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      k : ~astropy.units.Quantity
```suggestion
    k : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      particle : ~plasmapy.particles.Particle
```suggestion
    particle : `~plasmapy.particles.Particle`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      method : str, optional
```suggestion
    method : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      mass : ~astropy.units.Quantity
```suggestion
    mass : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      ndim : int
```suggestion
    ndim : `int`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      V : ~astropy.units.Quantity
```suggestion
    V : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      T : ~astropy.units.Quantity
```suggestion
    T : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      n : ~astropy.units.Quantity
```suggestion
    n : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      method : str, optional
```suggestion
    method : `str`, optional
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      omega_c : ~astropy.units.Quantity
```suggestion
    omega_c : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
> +    Vperp : ~astropy.units.Quantity, optional, keyword-only
```suggestion
    Vperp : `~astropy.units.Quantity`, optional, keyword-only
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
> +    T_i : ~astropy.units.Quantity, optional, keyword-only
```suggestion
    T_i : `~astropy.units.Quantity`, optional, keyword-only
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      r_Li : ~astropy.units.Quantity
```suggestion
    r_Li : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      n : ~astropy.units.Quantity
```suggestion
    n : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      particle : ~plasmapy.particles.Particle
```suggestion
    particle : `~plasmapy.particles.Particle`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      T_e: ~astropy.units.Quantity
```suggestion
    T_e : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      n_e: ~astropy.units.Quantity
```suggestion
    n_e : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      lambda_D : ~astropy.units.Quantity
```suggestion
    lambda_D : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      T_e : ~astropy.units.Quantity
```suggestion
    T_e : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      n_e : ~astropy.units.Quantity
```suggestion
    n_e : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      N_D : ~astropy.units.Quantity
```suggestion
    N_D : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      n : ~astropy.units.Quantity
```suggestion
    n : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      particle : ~plasmapy.particles.Particle
```suggestion
    particle : `~plasmapy.particles.Particle`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      ion : ~plasmapy.particles.Particle
```suggestion
    ion : `~plasmapy.particles.Particle`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      T_e: `~astropy.units.Quantity`
```suggestion
    T_e : `~astropy.units.Quantity`
```

2021-03-11 04:00 UTC, Tiger-Du commented on plasmapy/formulary/parameters.py
>      B: `~astropy.units.Quantity`
```suggestion
    B : `~astropy.units.Quantity`
```

2021-03-11 07:04 UTC, StanczakDominik commented
Wrong branch, sorry!

2021-03-11 15:58 UTC, namurphy commented
@StanczakDominik — Feel free to merge this if you're ready to make the release and this looks good to you!

2021-03-12 19:37 UTC, StanczakDominik approved these changes
Admittedly I skimmed things but I trust you guys

2021-03-12 19:37 UTC, merged