Lite versions of plasma dispersion function
PlasmaPy/PlasmaPy pull request #1473
Opened 2022-03-08 20:29 UTC by pheuer

Creates lite versions of the plasma dispersion function and its derivative.

This just eliminates input validation: future work necessary to cythonize these functions.

Necessary for #974

2022-03-16 17:31 UTC, rocco8773 commented
This is looking good, thanks for doing this.  The big item that needs to be done is writing tests.  Is this something you'd be up for doing?  If not, I can do it but won't have the time until after this week.

[`test_plasma_frequency.py`](https://github.com/PlasmaPy/PlasmaPy/blob/main/plasmapy/formulary/tests/test_plasma_frequency.py) is a good example of what to do to get the tests in order.  You essentiall need to:

1. Add the [`test_lite_function_binding`](https://github.com/PlasmaPy/PlasmaPy/blob/977438e7ea336965733917a670ad85874adfadc0/plasmapy/formulary/tests/test_plasma_frequency.py#L41) test
2. Add the [`test_lite_function_marking`](https://github.com/PlasmaPy/PlasmaPy/blob/977438e7ea336965733917a670ad85874adfadc0/plasmapy/formulary/tests/test_plasma_frequency.py#L46) test
3. Duplicate the [`TestPlasmaFrequencyLite`](https://github.com/PlasmaPy/PlasmaPy/blob/977438e7ea336965733917a670ad85874adfadc0/plasmapy/formulary/tests/test_plasma_frequency.py#L145) test class.

2022-03-16 19:35 UTC, pheuer commented
@rocco8773  Done!

2022-03-18 01:06 UTC, rocco8773 requested changes
Looking good so far.  This is just a review of the main functionality and I only have a few suggestions for the docstrings.

2022-03-18 01:06 UTC, rocco8773 commented on plasmapy/dispersion/dispersionfunction.py
> +    """
```suggestion
        Value of plasma dispersion function.

    See Also
    --------
    ~plasmapy.dispersion.dispersionfunction.plasma_dispersion_func

    """
```

2022-03-18 01:06 UTC, rocco8773 commented on plasmapy/dispersion/dispersionfunction.py
>  def plasma_dispersion_func(
Add to the "Examples" section of the docstring the following bit...

```rst
    For user convience
    `~plasmapy.dispersion.dispersionfunction.plasma_dispersion_func_lite`
    is bound to this function and can be used as follows:

    >>> plasma_dispersion_func.lite(0)
    1.7724538509055159j
    >>> plasma_dispersion_func.lite(1j)
    0.757872156141312j
    >>> plasma_dispersion_func.lite(-1.52+0.47j)
    (0.6088888957234254+0.33494583882874024j)
```

2022-03-18 01:06 UTC, rocco8773 commented on plasmapy/dispersion/dispersionfunction.py
> +    r"""
```suggestion
def plasma_dispersion_func_deriv_lite(zeta):
    r"""
```

For the same reason as `plasma_dispersion_func`.

2022-03-18 01:06 UTC, rocco8773 commented on plasmapy/dispersion/dispersionfunction.py
> +    The ":term:`lite-function`" version of
```suggestion
    The :term:`lite-function` version of
```

2022-03-18 01:06 UTC, rocco8773 commented on plasmapy/dispersion/dispersionfunction.py
> +    safeguards removed.
```suggestion
    but is intended for computational use and, thus, has all data
    conditioning safeguards removed.
```

2022-03-18 01:06 UTC, rocco8773 commented on plasmapy/dispersion/dispersionfunction.py
> +        dimensionless.
```suggestion
    zeta : :term:`numpy:array_like` of real or complex values
        Argument of the plasma dispersion function. ``zeta`` is
        dimensionless.
```

2022-03-18 01:06 UTC, rocco8773 commented on plasmapy/dispersion/dispersionfunction.py
> +    """
```suggestion
        First derivative of plasma dispersion function.

    See Also
    --------
    ~plasmapy.dispersion.dispersionfunction.plasma_dispersion_func_deriv

    """
```

2022-03-18 01:06 UTC, rocco8773 commented on plasmapy/dispersion/dispersionfunction.py
>  def plasma_dispersion_func_deriv(
Add to the "Examples" section of the docstring the following bit...

```rst
    For user convience
    `~plasmapy.dispersion.dispersionfunction.plasma_dispersion_func_deriv_lite`
    is bound to this function and can be used as follows:

    >>> plasma_dispersion_func_deriv.lite(0)
    (-2+0j)
    >>> plasma_dispersion_func_deriv.lite(1j)
    (-0.484255687717376...+0j)
    >>> plasma_dispersion_func_deriv.lite(-1.52+0.47j)
    (0.165871331498228...+0.445879788059350...j)
```

2022-03-18 01:08 UTC, rocco8773 commented on changelog/1473.feature.rst
> +respectively.
```suggestion
Created :term:`lite-functions`
`~plasmapy.dispersion.dispersionfunction.plasma_dispersion_func_lite` and
`~plasmapy.dispersion.dispersionfunction.plasma_dispersion_func_deriv_lite`
for `~plasmapy.dispersion.dispersionfunction.plasma_dispersion_func`
and `~plasmapy.dispersion.dispersionfunction.plasma_dispersion_func_deriv`
respectively.
```

2022-03-18 01:31 UTC, rocco8773 reviewed
Tests look good to me!  Just address my previous comments and I'll be happy to merge this.

Thanks for putting this together!

2022-03-18 17:33 UTC, merged