Minor edits to `README.md`
PlasmaPy/PlasmaPy pull request #1495
Opened 2022-03-22 19:07 UTC by namurphy

...includes using Eastern time instead of UTC, for consistency with the website.

Also intended to test #1492.

2022-04-19 07:09 UTC, StanczakDominik requested changes

2022-04-19 07:09 UTC, StanczakDominik commented on README.md
> +[citation instructions]: https://docs.plasmapy.org/en/latest/about/citation.html
I get the intention behind splitting the links off, but... I honestly think for short links and for one off links, keeping them in the main text body makes for a much cleaner writing experience. I'd say it's fine to keep repetitive abominations such as the extremely long calendar link in the above, though. I'll go through this and propose some adjustments in commit form.

2022-04-20 18:38 UTC, StanczakDominik approved these changes
Okay, nah, I give up, let's get it in 👍🏻

2022-04-20 22:03 UTC, namurphy commented
> Okay, nah, I give up, let's get it in 👍🏻 It's a definite improvement in terms of content and while I may not like the formatting, I don't think reverting that is worth the effort 😅

Thanks!  My original motivation for doing this came from doing `make linkcheck` for our docs to look for broken links...and I found it much easier to fix the broken links when they were all at the bottom of the file or in `docs/common_links.py`.  After you commented I realized that this reason is pretty irrelevant for `README.md` since it doesn't get checked with `make linkcheck`, so my motivation ended up changing to laziness.  I'm happy to get this merged now, and would be open to a reorganization of the links if we decide it would make it more maintainable in the future.

2022-04-20 22:04 UTC, merged