Thomson fitting example notebook
PlasmaPy/PlasmaPy pull request #1520
Opened 2022-04-18 17:58 UTC by pheuer

Creates an example ipynb for the Thomson fitting functionality

2022-08-08 18:33 UTC, rocco8773 requested changes
Can you add the notebook to the `.. nbgallery:` directive in `docs/ad/diagnostics/thomson.rst`?

2022-08-18 21:45 UTC, pheuer commented
> Can you add the notebook to the `.. nbgallery:` directive in `docs/ad/diagnostics/thomson.rst`?

Done 

Note that the codespell error is expected (catching a couple variable names that are not accidental)

2022-08-24 13:01 UTC, pheuer commented
@StanczakDominik Thanks - good idea to try but it looks like `ans` is still in the list of potentially misspelled words

```
./docs/notebooks/diagnostics/thomson_fitting.ipynb:412: ans ==> and
./docs/notebooks/diagnostics/thomson_fitting.ipynb:413: ans ==> and
./docs/notebooks/diagnostics/thomson_fitting.ipynb:538: ans ==> and
./docs/notebooks/diagnostics/thomson_fitting.ipynb:539: ans ==> and
```

2022-08-24 14:20 UTC, StanczakDominik commented
Just add it to the list of common "typos" in `setup.cfg`, then? It should be under `[codespell]`.

2022-08-24 14:56 UTC, pheuer commented
> Just add it to the list of common "typos" in `setup.cfg`, then? It should be under `[codespell]`.

Ooh that works, thanks!! 

I notice that all my charged particle radiography notebooks have been excluded from codespell - does that mean my spelling is beyond reproach or so awful as to not be worth fixing? ;) 

```
*charged_particle*.ipynb
```

2022-08-24 15:04 UTC, StanczakDominik commented
Oh LMAO, you're right! `git blame` identifies @namurphy's [016ea25](https://github.com/PlasmaPy/PlasmaPy/pull/1611/commits/016ea25ecc2313d92c89f7c03e5b8b207f8f60fc) as the culprit commit, where it's attached without explanation. What happened there? 😆

2022-08-24 15:17 UTC, pheuer commented
My guess is my notebooks contain so many spelling errors it was easiest just to skip them for now haha

2022-08-24 15:27 UTC, StanczakDominik commented
It's weird, I removed them from `skip` locally and I'm getting errors on words that I can't find in the actual notebooks. 😕

2022-08-24 18:09 UTC, namurphy commented
> Oh LMAO, you're right! `git blame` identifies @namurphy's [016ea25](https://github.com/PlasmaPy/PlasmaPy/pull/1611/commits/016ea25ecc2313d92c89f7c03e5b8b207f8f60fc) as the culprit commit, where it's attached without explanation. What happened there? 😆

If I'm remembering correctly, it was because the notebooks were pre-executed, and codespell was finding "misspellings" in the embedded png files.

2022-08-24 19:15 UTC, pheuer commented
> If I'm remembering correctly, it was because the notebooks were pre-executed, and codespell was finding "misspellings" in the embedded png files.

Oh, that makes sense!

2022-08-25 04:16 UTC, StanczakDominik commented
OoooooooOOOOOOOOH. That also explains why I couldn't grep out those phrases in the version I was editing via jupytext - it just gives me the text input.

2022-08-29 14:03 UTC, pheuer commented
@rocco8773 @namurphy This PR has been in the review phase for a long time. I suggest we either 1) do the review this week or 2) do a light review for major issues and then merge this and fix minor issues later. My concern is that this Thomson fitting functionality is pretty complicated is therefore having it in the package is functionally useless without this example notebook to explain how it works.

2022-08-29 15:56 UTC, namurphy reviewed
Thanks for the reminder, @pheuer! I read through the notebook and, with the caveat that I know very little about Thomson scattering diagnostics, it looks pretty close to ready to merge.  @rocco8773 — would you have a chance to look through this soon too?

2022-08-29 15:56 UTC, namurphy commented on docs/notebooks/diagnostics/thomson_fitting.ipynb
> +    "Thomson scattering can be either non-collective (dominated by single electron scattering) or collective (dominated by scattering off of electron plasma waves (EPW) and ion acoustic waves (IAW).
```suggestion
    "Thomson scattering can be either non-collective (dominated by single electron scattering) or collective (dominated by scattering off of electron plasma waves (EPW) and ion acoustic waves (IAW). In the non-collective regime, the scattering spectrum contains a single peak. However, in the collective regime the spectrum contains separate features caused by the electron and ion populations (corresponding to separate scattering off of EPW and IAW). These features exist on different scales: the EPW feature is dim but covers a wide wavelength range, while the IAW feature is bright but narrow. They also encode partially-degenerate information (e.g., the flow velocities of the electrons and ions respectively). The two features are therefore often recorded on separate spectrometers and are fit separately. \n"
```

2022-08-30 18:20 UTC, namurphy approved these changes

2022-08-30 20:08 UTC, namurphy commented
@pheuer — Is there anything else you wanted to do before we merged this?  If not, please feel free to merge it, or I could do so soon!

2022-08-30 20:09 UTC, pheuer commented
Nope, let's do it!

2022-08-30 20:09 UTC, merged