Modified the Tracker class in ~plasmapy/diagnostics/charged_particle_…
PlasmaPy/PlasmaPy pull request #1830
Opened 2022-12-11 05:52 UTC by Sobeskes

…radiography.py to run in parallel

## Description

Modified ~plasmapy/diagnostics/charged_particle_radiography.py to split array of simulated particles into partitions that are then run in parallel
Added tests to ~plasmapy/diagnostics/tests/test_charged_particle_radiography.py that test performance on extremely large inputs; extremely large tests are left commented to not dramatically slow down the test suite.

## Motivation and context

@pheuer identified this as an embarrassingly parallelizable problem in #1728. In theory, by parallelizing this step of the simulation we should see a significant increase in speed performance.

## Related issues
This issue was brought up in #1728

2022-12-11 19:32 UTC, StanczakDominik commented
Going to run pre-commit.ci on this first...

pre-commit.ci autofix

2022-12-11 19:37 UTC, StanczakDominik requested changes
> In theory, by parallelizing this step of the simulation we should see a significant increase in speed performance.

In theory, sure! I'm not sure this approach is going to accomplish that - happy to be convinced with data, though! Did you try to benchmark this before and after this change? What kind of speedup, if any, did you get?

This is not really a "reject" based on "needing changes to the code", rather on needing to prove that this works as intended!

2022-12-12 19:01 UTC, Sobeskes commented
Absolutely, I totally understand! Right now, when testing on extremely large test cases, there seems to be a modest increase of speed, but definitely not what you'd hope to see. My classes are finishing up right now, but when I get more free time I'd be very interested in coming back to see if dask would be the right solution for this. In the mean time, I made a minor typo change in order to include the CI tests in my final report.

2022-12-12 19:22 UTC, StanczakDominik commented
That makes sense!

Would you mind, then, if I converted this PR to draft for now? I'm trying to be better about reviewing/merging stuff in a timely manner and it helps to keep that effort focused 😉

2022-12-13 19:57 UTC, StanczakDominik commented
I'm going to take that as a yes, we can always revert the draftiness 😉

2022-12-14 00:55 UTC, Sobeskes commented
Absolutely! Sorry for being slow with replying., finals season has been eventful.

2022-12-14 04:09 UTC, StanczakDominik commented
No worries whatsoever. Good luck with the finals! :)

2025-04-12 04:46 UTC, closed without merging