Add back in scattering + stopping to code
PlasmaPy/PlasmaPy pull request #1875
Opened 2023-01-06 21:21 UTC by pheuer

This PR adds particle scattering and stopping in dense matter to the charged particle radiography Tracker class. This capability is important for charged particle radiography in dense plasmas where these effects significantly affect the radiograph. 

Builds on #1799, so merge that first.

Note: should compare this implementation of scattering + stopping to the MPRAD code described here: https://aip.scitation.org/doi/full/10.1063/1.5123392

Replaces a previous PR (#1802) because I needed to completely refactor after #1799

2023-01-07 04:45 UTC, StanczakDominik commented
1799 is merged, did you mean another PR there, or...?

2023-01-09 14:50 UTC, pheuer commented
> 1799 is merged, did you mean another PR there, or...?

#1802 is the one I'm replacing: this PR needed to be refactored after 1799 got merged and, after ending up in a bit of a git tangle, I ended up just making a new branch from main and copying over the changes.

2023-01-09 17:19 UTC, StanczakDominik requested changes
A couple quick fixes for now:

2023-01-09 17:19 UTC, StanczakDominik commented on plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
> +
```suggestion
```

You can actually just use `np.random.normal(scale=sigmas)`!

2023-01-09 17:19 UTC, StanczakDominik commented on plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
> +    Tablulated proton and electron stopping power curves can be found here:
```suggestion
    Tabulated radiation lengths can be found here:
        https://pdg.lbl.gov/2022/AtomicNuclearProperties/index.html

    Tabulated proton and electron stopping power curves can be found here:
```

2023-01-09 17:19 UTC, StanczakDominik commented on plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
> +                    thetas = draw_from_normal(sigmas)  # polar angle
```suggestion
                    thetas = np.random.normal(scale=sigmas)  # polar angle
```

2025-04-12 04:46 UTC, closed without merging