Change minimum version of Python from 3.8 to 3.9
PlasmaPy/PlasmaPy pull request #1885
Opened 2023-01-12 15:32 UTC by namurphy

## Description

This PR changes config files and applies changes from `pyupgrade` and `ruff` for the switch from Python 3.8+ to Python 3.9+. 

This PR should be reviewed and merged after the release of `v2023.1.0`.

## Motivation and context

[NumPy Enhancement Proposal 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) lays out a recommended community schedule for dropping support of old versions of packages.  As per the schedule, Python 3.8 support can be dropped for releases after April 14, 2023.

## Related issues

Closes #1796. Cross-references: #1262, #980

2023-01-12 15:42 UTC, namurphy commented
- [ ] Change the GitHub repo setting to not require 'Python 3.8, all tests, code coverage'

2023-01-12 17:07 UTC, namurphy commented on pyproject.toml
> +  "pandas>=1.2",
I think it was the `pandas` dependency that was causing problems on the tests with the minimum versions.  For most of the dependencies that I changed, I looked for a release that was roughly two years old and set that as the minimum version, which is what NEP 29 recommends doing for NumPy and is probably a good balance between reducing maintenance burden and having a wide enough window of allowed package versions.

2023-01-14 00:09 UTC, namurphy commented
**Important note:** I temporarily turned off the branch protection rule for requiring the Python 3.8 minimal dependencies check to pass before merging.  After this PR is merged, we'll need to re-enable it on the Python 3.9 equivalent (and perhaps some of the other checks too).  We'll need to do the same thing for switching the tests to nox as well.

2023-01-14 08:19 UTC, StanczakDominik requested changes
LGTM! A couple minor issues. I'll run through this to check the `future` imports.

2023-01-14 08:19 UTC, StanczakDominik commented on docs/common_links.rst
> +.. |minpython| replace:: 3.9
Wow.

2023-01-14 08:19 UTC, StanczakDominik commented on plasmapy/analysis/fit_functions.py
> +        param_errors: tuple[float, ...] = None,
Shouldn't we also go through `future` imports, btw? see if we can't remove them? Or would pyupgrade remove them by itself?

2023-01-14 08:22 UTC, StanczakDominik commented on plasmapy/analysis/fit_functions.py
> +        param_errors: tuple[float, ...] = None,
Ah. Guess not; the only `__future__` imports we have are `from __future__ import annotations`, and [that still isn't going to be the default for a while](https://docs.python.org/3/library/__future__.html#id2).

2023-01-14 08:26 UTC, StanczakDominik approved these changes
Applied the changelog merge; feel free to revert it if you prefer doing them separately, though.

2023-01-14 14:59 UTC, namurphy commented on changelog/1885.removal.rst
> +Changed the minimum required version of Python from 3.8 to 3.9.
Yeah, I wasn't sure where to put this one!  Happy to go with `breaking` instead.

2023-01-14 15:00 UTC, namurphy commented
Thank you for the reviews!

2023-01-14 15:00 UTC, merged